"""empty message

Revision ID: 1e5a5f193574
Revises: 8509642db78b
Create Date: 2022-09-10 20:43:38.344265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5a5f193574'
down_revision = '8509642db78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show_items', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'show_items', 'Shows', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show_items', type_='foreignkey')
    op.alter_column('show_items', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
