"""empty message

Revision ID: 8d9f85fb7f20
Revises: 1e5a5f193574
Create Date: 2022-09-10 20:57:17.393860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9f85fb7f20'
down_revision = '1e5a5f193574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show_items', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('show_items', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show_items', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('show_items', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
