"""empty message

Revision ID: e5e1d70854f1
Revises: 823c2d3feb35
Create Date: 2022-09-10 21:49:19.532585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e1d70854f1'
down_revision = '823c2d3feb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_items',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], name='show_items_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Shows.id'], name='show_items_show_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venues.id'], name='show_items_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id', name='show_items_pkey')
    )
    # ### end Alembic commands ###
